# Generated by Django 6.0.1 on 2026-01-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_networknode_options_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networknode',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['release_date']},
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='node_type',
        ),
    ]
